CREATE TABLE [dbo].[ADLog](
	[LogNumber] [int] IDENTITY(1,1) NOT NULL,
	[Keywords] [varchar](100) NULL,
	[DateandTime] [varchar](100) NULL,
	[Source] [varchar](500) NULL,
	[EventID] [int] NULL,
	[TaskCategory] [varchar](50) NULL,
	[User] [varchar](50) NULL,
	[Computer] [varchar](200) NULL,
	[Message] [varchar](4000) NULL
)

CREATE TABLE [dbo].[LogonData](
	[LogNumber] [int] NULL,
	[DateandTime] [varchar](100) NULL,
	[Computer] [varchar](200) NULL,
	[SecurityID] [varchar](200) NULL,
	[AccountDomain] [varchar](200) NULL,
	[WorkstationName] [varchar](200) NULL,
	[SourceNetworkAddress] [varchar](200) NULL,
	[SourcePort] [varchar](200) NULL
)

CREATE procedure [dbo].[usp_transformLogs] AS

BEGIN

DECLARE @LASTLOGNUMBER INT
SET @LASTLOGNUMBER = (SELECT ISNULL(MAX(LOGNUMBER),0)  FROM LOGONDATA)

DECLARE @MAXLOGNUMBER INT
SET @MAXLOGNUMBER = (SELECT ISNULL(MAX(LOGNUMBER),0)  FROM ADLog)


SELECT T.*, S.VALUE INTO #TEMP_LOGS FROM DBO.ADLOG T CROSS APPLY STRING_SPLIT(T.[MESSAGE], CHAR(10)) S  WHERE LOGNUMBER> @LASTLOGNUMBER ORDER BY LOGNUMBER 

DELETE FROM  #TEMP_LOGS  WHERE VALUE = '' OR VALUE NOT LIKE '%:%'


--- FOR Loop to Iterate----

DECLARE @CNT INT ;
SET @CNT = @LASTLOGNUMBER
WHILE @CNT < @MAXLOGNUMBER
BEGIN

  DECLARE @TASKCATEGORY VARCHAR(50)
  SET @TASKCATEGORY = (SELECT TaskCategory FROM  ADLog WHERE LogNumber=@CNT)

  IF @TASKCATEGORY='Logon'
   
   BEGIN
      SELECT *, LTRIM(RTRIM(LEFT(VALUE, CHARINDEX(':', VALUE) - 1))) AS TITLE, 
      LTRIM(RTRIM(REVERSE(LEFT(REVERSE(VALUE), CHARINDEX(':', REVERSE(VALUE)) - 1)))) AS [DATA] INTO #FINALDATA
      FROM #TEMP_LOGS  WHERE LOGNUMBER =@CNT  

      INSERT INTO LOGONDATA
      SELECT  LOGNUMBER,DATEANDTIME,COMPUTER,NULL, NULL, NULL, NULL, NULL FROM #FINALDATA  GROUP BY DATEANDTIME,COMPUTER,LOGNUMBER


      UPDATE LOGONDATA 
      SET SECURITYID= B.[DATA]
      FROM  #FINALDATA B WHERE  B.TITLE LIKE '%SECURITY ID%'AND  B.LOGNUMBER =@CNT AND B.[DATA] NOT LIKE '%NULL%'

      UPDATE LOGONDATA 
      SET [ACCOUNTDOMAIN]= B.[DATA]
      FROM  #FINALDATA B WHERE  B.TITLE LIKE '%ACCOUNT DOMAIN%'AND  B.LOGNUMBER =@CNT AND B.[DATA] NOT LIKE '%-%'

      UPDATE LOGONDATA 
      SET WORKSTATIONNAME= B.[DATA]
      FROM  #FINALDATA B WHERE  B.TITLE LIKE '%WORKSTATION NAME%'AND  B.LOGNUMBER =@CNT

      UPDATE LOGONDATA 
      SET SOURCENETWORKADDRESS= B.[DATA]
      FROM  #FINALDATA B WHERE  B.TITLE LIKE '%SOURCE NETWORK ADDRESS%'AND  B.LOGNUMBER =@CNT

      UPDATE LOGONDATA 
      SET SOURCEPORT= B.[DATA]
      FROM  #FINALDATA B WHERE  B.TITLE LIKE '%SOURCE PORT%'AND  B.LOGNUMBER =@CNT


      DROP TABLE #FINALDATA
    END
	SET @CNT=@CNT+1
	END
	DROP TABLE #TEMP_LOGS
END;
GO


